### ISSUE TITLE
[Crash] App freezes with white screen after device is unlocked

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#901] opened 2021-06-17 18:05 UTC
1. Open app, leave homescreen open with active project
2. Lock device
3. Unlock device
4. Screen appears blank/white or shows splash screen

More details to follow.

**Comment by gino-m** [comment] 2021-06-22 22:38
Saw the same happen with `getToken() -> BAD_AUTHENTICATION` in log when user needed to verify identity because account was being used on multiple devices. We should catch and report these exceptions.

**Comment by gino-m** [comment] 2021-07-08 19:38
This also happens after minimizing and reopening the app on:
```
2021-07-08 19:34:18.964 19995-19995/com.google.android.gnd E/RxDebug: Caused by: java.lang.Throwable: caused by java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
2021-07-08 19:34:18.964 19995-19995/com.google.android.gnd E/RxDebug:     at com.google.android.gnd.persistence.local.room.dao.UserDao_Impl.update(UserDao_Impl.java:148)
2021-07-08 19:34:18.964 19995-19995/com.google.android.gnd E/RxDebug:     at com.google.android.gnd.persistence.local.room.dao.UserDao_Impl.update(UserDao_Impl.java:27)
```

In that case, the `nav_host_fragment` is not restored; it contains an empty FrameLayout.

@scolsen Related to your recent issue perhaps?

**Comment by gino-m** [comment] 2023-02-27 17:49
Haven't seen this happening anymore. Closing as "can't reproduce"

**Comment by gino-m** [comment] 2023-06-21 16:19
@shobhitagarwal1612 If you're able to repro any chance you could investigate when you have a free cycle?

**Comment by shobhitagarwal1612** [comment] 2023-06-21 17:43
Looking into it.

**Comment by shobhitagarwal1612** [comment] 2023-06-24 05:07
I'm unable to repro this issue now. Closing it.

**Comment by gino-m** [comment] 2023-09-25 14:24
This just happened to me while developing on Pixel 7 connected via USB 3x in a row, reopening.

**Comment by gino-m** [comment] 2023-09-25 14:46
Note: this appears to be happening when the app is being restarted while in the background. This is reproducible by relaunching the app from AS while the device asleep. This may be similar to what happens when the error occurs when not debugging via USB; the app may get destroyed in the background and restarted on wake.

**Comment by shobhitagarwal1612** [comment] 2023-10-01 06:26
I'm able to reproduce this by following the steps mentioned in the above comment.

The issue seems to be that StartupFragment initializes the flow in `onAttach` method which isn't called if the device wakes up after sleep. Only `onStart()` and `onResume()` are called.

**Closed** 2023-10-01 20:56 UTC
Labels: type: bug, priority: p1
