### ISSUE TITLE
[Nav menu] Update style and show profile info in the side panel menu and sign out

### ISSUE THREAD

**Issue by rawbzz** [google/ground-android#2238] opened 2024-02-14 19:35 UTC
https://www.figma.com/file/r2uGtyOiWoDa29za7DNuUc/Ground-Acacia-UX?type=design&node-id=5234%3A20396&mode=design&t=awQtAX2VmKHcituF-1

**Comment by rawbzz** [comment] 2024-02-14 20:32
<img width="730" alt="Screenshot 2024-02-14 at 3 29 13 PM" src="https://github.com/google/ground-android/assets/108412767/b5a23dc6-fa6b-41c3-bb62-358e9c6758c2">

**Comment by gino-m** [comment] 2024-02-14 20:52
@amegantz Is "Profile information" the correct header here?

**Comment by amegantz** [comment] 2024-02-15 04:46
I'd move the user's name to the header and get rid of the "Profile information" line entirely

**Comment by rawbzz** [comment] 2024-02-15 19:48
<img width="692" alt="Screenshot 2024-02-15 at 2 47 46 PM" src="https://github.com/google/ground-android/assets/108412767/794e6254-7753-425a-a722-6b86c43869f0">

Like this? I kept the name in the dialog because if a name is super long, it might not look as nice in the header area

**Comment by amegantz** [comment] 2024-02-16 19:25
Yes, exactly, though you do raise a good point about super-long names. We can truncate if needed. I think if this menu becomes more robust, we can revisit a header like "Profile details," but for now, it seems superfluous.

Also, "Sign out" should be two words if used as a verb, like in a CTA (I updated it in the Figma).

**Comment by gino-m** [comment] 2024-04-18 16:50
Duplicate of #2397

**Closed by gino-m** 2024-04-18 16:50 UTC
Labels: type: fr
