### ISSUE TITLE
[Crash] Fatal Exception: java.util.NoSuchElementException in DataCollectionViewModel

### ISSUE THREAD

**Issue by jcqli** [google/ground-android#2415] opened 2024-03-29 13:54 UTC
Crash reported by Firebase [here](https://firebase.corp.google.com/project/of-ground/crashlytics/app/android:org.openforis.ground/issues/f1414d80a6320fe60cc3bcc2f0062b27?time=1710979200000:1711497599000&types=crash&sessionEventKey=65FDA22F001800011633E2C2F885CBE3_1927654101421404726)

```
Fatal Exception: java.util.NoSuchElementException: List is empty.
       at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:214)
       at com.google.android.ground.ui.datacollection.DataCollectionViewModel.<init>(DataCollectionViewModel.kt:136)
       at com.google.android.ground.DaggerGroundApplication_HiltComponents_SingletonC$ViewModelCImpl$SwitchingProvider.get(DaggerGroundApplication_HiltComponents_SingletonC.java:1480)
       at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory$2.createViewModel(HiltViewModelFactory.java:132)
       at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory$2.create(HiltViewModelFactory.java:103)
       at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:170)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:184)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:150)
       at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:53)
       at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:35)
       at com.google.android.ground.ui.datacollection.DataCollectionFragment.getViewModel(DataCollectionFragment.kt:49)
       at com.google.android.ground.ui.datacollection.DataCollectionFragment.onViewCreated(DataCollectionFragment.kt:78)
       at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3147)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
       at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
       at android.os.Handler.handleCallback(Handler.java:959)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loopOnce(Looper.java:232)
       at android.os.Looper.loop(Looper.java:317)
       at android.app.ActivityThread.main(ActivityThread.java:8501)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

**Comment by shobhitagarwal1612** [comment] 2024-04-01 14:58
Duplicate of https://github.com/google/ground-android/issues/2408

**Closed by shobhitagarwal1612** 2024-04-01 14:58 UTC
Labels: type: bug
