### ISSUE TITLE
[Offline map imagery] Fetch tiles in parallel to improve offline download performance

### ISSUE THREAD

**Issue by gino-m** [google/ground-android#1704] opened 2023-06-13 12:13 UTC

**Comment by gino-m** [comment] 2024-03-20 10:48
@sufyanAbbasi @shobhitagarwal1612 Can you please coordinate one this one?

**Comment by shobhitagarwal1612** [comment] 2024-04-20 03:17
Duplicate of https://github.com/google/ground-android/issues/2355

**Closed by shobhitagarwal1612** 2024-04-20 03:17 UTC
Labels: type: fr
