### ISSUE TITLE
Add unit tests for firebase schema converters

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-android#1726] opened 2023-06-27 04:50 UTC
package name `ground.persistence.remote.firebase.schema`

- [x] AuditInfoConverter
- [x] GeometryConverter
- [ ] JobConverter
- [ ] LoiConverter
- [ ] LoiMutationConverter
- [ ] MultipleChoiceConverter
- [ ] OptionConverter
- [ ] QuerySnapshotConverter
- [ ] SubmissionConverter (needs more coverage for remaining task types)
- [x] SubmissionMutationConverter (#1727)
- [ ] SurveyConverter
- [ ] TaskConverter
- [x] TermsOfServiceConverter
- [x] UserConverter

**Comment by gino-m** [comment] 2024-01-17 22:37
Duplicate of #2134

**Closed by gino-m** 2024-01-17 22:37 UTC
Labels: type: code health
