### ISSUE TITLE
Incorrect LocationOfInterest label in DataCollectionFragment

### ISSUE THREAD

**Issue by rachaprince** [google/ground-android#2046] opened 2023-11-06 18:58 UTC
LocationOfInterest label in DataCollectionFragment should use the format described in:
https://github.com/google/ground-platform/issues/1242

**Comment by jcqli** [comment] 2024-03-04 18:57
Duplicate of https://github.com/google/ground-android/issues/2291

**Closed by jcqli** 2024-03-04 18:57 UTC
Labels: type: bug
